"""empty message

Revision ID: 052c48b4030e
Revises: cc6dab2f2f95
Create Date: 2022-05-31 21:53:46.194742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052c48b4030e'
down_revision = 'cc6dab2f2f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column(
        'todolists_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['todolists_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todolists_id')
    # ### end Alembic commands ###
